INSERT INTO HR.MANAGERS_906 (MANAGER_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID) VALUES
	 (100,'Alex','Brown',80),
	 (101,'Alex','Brown',80),
	 (NULL,NULL,NULL,1),
	 (NULL,NULL,NULL,2),
	 (5,NULL,NULL,6);
